### PR TITLE
localize the country based on the origin country

### PR DESCRIPTION
**Pull request by dbaq**
Hi @cainlevy,

I am not sure if you are still maintaining this project but here is a pull request. It is a large pull request due to all the translation files. The only interesting commit is this one fd0133f, I localize the country based on the origin country. Some translations may not contain all the translated countries (like Afghanistan), that's why I fallback to US if not found. I also added some unit tests.

The translations come from http://cldr.unicode.org/index which is the most reliable source AFAIK.

Let me know if you have any questions.

Cheers

### CODE REVIEW

**Comment by cainlevy** [comment]
Hi @dbaq, thanks for the thorough pull request! I'd forgotten about that `TODO`.

I may need a few days to properly consider the change. One of the things I'd like to explore is building this feature as an optional dependency on a gem that already specializes in geography translations (e.g. https://github.com/jim/carmen). What do you think?

**Comment by dbaq** [comment]
IMO, I would not consider this feature as optional. For international mails, the destination country should always be localized in the origin country locale.

Which use case do you have in mind where the country localization should be optional?

**Comment by dbaq** [comment]
Also, I am thinking about a way to print the country even if the origin country equals the address country. When I print a document to send internationally, my address as a sender should have United States on it so the recipient knows the full address. Would love to have your thoughts on that as well, that might be outside this pull request scope though.

**Comment by cainlevy** [comment]
>  I would not consider this feature as optional. For international mails, the destination country should always be localized in the origin country locale.

Seems reasonable.

My biggest hesitation right now is that this pull request makes Snail an expert on country names. I'd like to think this is a solved problem and we could depend on another gem, but github.com/jim/carmen doesn't seem to have as much data as you've gathered from CLDR.

On the other hand, I have to consider whether it's better for Snail to [minimize its dependencies](https://www.mikeperham.com/2016/02/09/kill-your-dependencies/) and provide a complete solution.

>  I am thinking about a way to print the country even if the origin country equals the address country. When I print a document to send internationally, my address as a sender should have United States on it so the recipient knows the full address.

If you're sending a return address to someone, should the country be printed as if the origin is wherever the recipient lives?

I'd also be happy to consider another issue or pull request that forces the country line to print.

**Comment by cainlevy** [comment]
Okay, I think I'm happy for Snail to take ownership of country name localization. Seems like the best current option.

I'll accept this once I'm confident it will perform well.

**Comment by dbaq** [comment]
Hi @cainlevy, thank you.

About the performances, I believe it should fine. The disk time won't be an issue since if you are making multiple access, the file will already be cached. If somebody reports performance issue, I'd be happy to dig into it and propose another solution.

>>I am thinking about a way to print the country even if the origin country equals the address country. When I print a document to send internationally, my address as a sender should have United States on it so the recipient knows the full address.

>If you're sending a return address to someone, should the country be printed as if the origin is wherever the recipient lives?
>I'd also be happy to consider another issue or pull request that forces the country line to print.

It is debatable, that's why I would like to introduce some options to be more flexible about whether hiding or not the country field, which locale should be used to translate the country, etc. But I will open an issue first so we can discuss and agree before opening a PR, probably mid next week.

**Comment by cainlevy** [comment]
Sorry for the delay, I wanted to take a look at the `translated_country` performance. I'm convinced that we can make this work with a tweak to the implementation.

## script

benchmarks on a 3.3GHz desktop with SSD

```
path = File.join(File.dirname(File.expand_path(__FILE__)), "/assets/DE.yml")
countries = File.readlines(path).map{|l| l.split(':').first }

Benchmark.ips do |x|
  x.config(time: 5, warmup: 2)

  x.report("YAML"){
    origin = countries.sample
    YAML.load_file(path)[origin]
  }

  x.report("GREP"){
    origin = countries.sample
    File.readlines(path).grep(/^#{origin}:/)[0].split(': ').last
  }

  x.report("FIND"){
    origin = countries.sample
    File.readlines(path).find{|l| l.match(/^#{origin}:/)}.split(': ').last
  }

  x.report("MATCH"){
    origin = countries.sample
    File.read(path).match(/^#{origin}: (.*)$/)[1]
  }

  x.compare!
end
```

## results

```
Calculating -------------------------------------
                YAML    39.000  i/100ms
                GREP   811.000  i/100ms
                FIND   160.000  i/100ms
               MATCH     4.140k i/100ms
-------------------------------------------------
                YAML    411.516  (± 1.9%) i/s -      2.067k
                GREP      8.686k (± 0.9%) i/s -     43.794k
                FIND      1.715k (± 3.6%) i/s -      8.640k
               MATCH     47.274k (± 1.2%) i/s -    240.120k

Comparison:
               MATCH:    47273.9 i/s
                GREP:     8686.1 i/s - 5.44x slower
                FIND:     1714.5 i/s - 27.57x slower
                YAML:      411.5 i/s - 114.88x slower
```

**Comment by cainlevy** [comment]
released as v2.0.0. thanks @dbaq!

**Comment by dbaq** [comment]
Dayumm, I had no idea YAML was that slow. Good job for benchmarking and fixing it. 🍻

**Pull request merged**
